trigger: none
# this is being defined in app-ci pipeline
resources:
  pipelines:
  - pipeline: deployment   # Name of the pipeline resource
    source: build # Name of the pipeline referenced by the pipeline resource

    # Trigger always. For example, on build deploy
    # trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

    trigger:
      stages:
        - Test
    # # Trigger by condition. For example, with Tag: (UAT/PROD) and Branch : Master, then deploy on UAT
    # trigger:
    #   tags:
    #     - Production
    #     - Signed
    #   branches:
    #     include: 
    #     - releases/*
    #     exclude:
    #     - releases/old*
    #   stages:
    #     - PreProduction
    #     - Production
steps:
  - script: echo 'Build completed, now artifact will be downloaded'
  - task: downloadpipelineartifact@2
    inputs:
      source: 'current'
      project: azure-pipeline-demo
      pipeline: 17
      prefertriggeringpipeline: true
      runversion: latest
      path: $(Build.SourcesDirectory)

  - task: Bash@3
    inputs:
      targetType: inline
      script: |

        echo "Current directory"
        echo $PWD

        echo "Working directory :"
        echo $(System.SourcesDirectory)

        echo "listing files"
        ls

        echo $(cat $(System.SourcesDirectory)/src/index.html)

        echo "Switching to ArtifactStagingDirectory"
        cd $(Build.ArtifactStagingDirectory)
        echo $PWD

        echo "listing files"
        ls

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/src'
      api_location: 'api'
      output_location: ''
      azure_static_web_apps_api_token: "c805a9a0e530655ec27fdc35f26a89bf0ee9142f095b1ded340859b79b3f20f60-36811deb-9515-4f55-93de-51efa92fd99000f11778"



