# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: config
    type: string
    default:'test3'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world! - ${{parameters.config}}
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: ServiceConnection-subscription
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
      az pipelines variable-group creat --name var-group --variables env='test' env1='test2' env2=${{parameters.config}}

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
