# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: config
    type: string
    default: 'test3'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world! - ${{parameters.config}} - $(System.TeamFoundationCollectionUri)
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: ServiceConnection-subscription
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      echo cli-2 : - $(System.AccessToken) -
      echo $(System.AccessToken) | az devops login
      az account show
      echo az devops configure - $(System.TeamFoundationCollectionUri) - $(System.TeamProject)
      az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
      echo 'az devops variable-group'
      az pipelines variable-group create --name var-group --variables env='test' env1='test2' env2=${{parameters.config}} --authorize true --detect true --subscription 7fe50eb0-0f9b-4400-b7b4-cd2881c5bb06

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
